/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package okbuck.ep.test;

import com.google.common.collect.ImmutableList.Builder;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
